Fix in google maps search if no location
inbo/vespa-watch pull request #542
Opened 2023-09-20 10:37 UTC by IT-FirmBV

2023-09-20 13:02 UTC, peterdesmet requested changes
Left some remarks, can you investigate?

2023-09-20 13:02 UTC, peterdesmet commented on assets/js/iasset.js
> +                $(document).find($('.close-button > button')).on('click', function () {
I don't understand why this is new, it was already implemented as such in https://github.com/inbo/vespa-watch/blob/66a487fedbd96db708cdfa4143fc44141b254639/assets/js/iasset.js#L351C17-L352C65

2023-09-20 13:04 UTC, peterdesmet commented
I notice https://github.com/IT-FirmBV/vespa-watch/tree/gh-pages is [28 commits behind](https://github.com/IT-FirmBV/vespa-watch/compare/gh-pages...inbo:vespa-watch:gh-pages) our gh-pages branch. Please pull in the latest changes first and then apply the changes that implement `Fix in google maps search if no location`.

2023-09-21 07:52 UTC, IT-FirmBV commented on assets/js/iasset.js
> -                            '<div class="close-button">' +
Problem was caused because our repo was behind. Will be updated with new pull request.

2023-09-21 07:53 UTC, IT-FirmBV commented on assets/js/iasset.js
> +                $(document).find($('.close-button > button')).on('click', function () {
Same reason as the previous question, we were behind on repo.

2023-09-21 07:53 UTC, IT-FirmBV commented on assets/js/iasset.js
> +})(jQuery);
Will be added on new pull request.

2023-09-21 08:34 UTC, peterdesmet commented on assets/js/iasset.js
> +                $('#' + selector).siblings('.pac-card').addClass('d-none');
I don't think the `pac-card` div is used anymore, so this line can be removed?

2023-09-21 10:30 UTC, IT-FirmBV commented on assets/js/iasset.js
> +                $('#' + selector).siblings('.pac-card').addClass('d-none');
Removed in new PR.

2023-09-21 12:36 UTC, peterdesmet approved these changes

2023-09-21 12:36 UTC, merged