544 update website
inbo/vespa-watch pull request #545
Opened 2023-09-22 10:02 UTC by CatoCoordinator

@peterdesmet @PietrH , is het mogelijk om deze wijzigingen goed te keuren? Bedankt

2023-09-26 06:53 UTC, peterdesmet requested changes
Zie opmerkingen

2023-09-26 06:53 UTC, peterdesmet commented on pages/nl/faq.md
> +{:id="Nest in Brussel, Wallonië of Nederland"}
De `id` dient als een verwijzing binnen de pagina en moet geschreven zijn met kleine letters en liggende streepjes. Hier zou ik kiezen voor `nest-buiten-vlaanderen`

2023-09-26 06:53 UTC, peterdesmet commented on pages/nl/faq.md
> +Dit platform Vespa-Watch monitort echter enkel nesten in **Vlaanderen** (België), dus niet nesten die gelegen zijn in Brussel, Wallonië of Nederland.
Ik zou "echter" laten vallen.

2023-09-26 06:53 UTC, peterdesmet commented on pages/nl/faq.md
> +Best kan je je nest melden via volgende sites indien het nest zich bevindt in:
Er hoeft geen nieuwe lijn gestart te worden voor nieuwe zinnen.

2023-09-26 06:53 UTC, peterdesmet commented on pages/nl/faq.md
> +- **Nederland**: [Waarnemingen.nl](https://waarneming.nl/go/vespa-velutina/ )
Geen spaties voor het sluitend haakje

2023-09-26 06:53 UTC, peterdesmet commented on pages/nl/get-involved.md
> +Het protocol van zenderen Aziatische hoornaar is beschikbaar via deze [link](https://pureportal.inbo.be/nl/publications/output-2023-protocol-zenderen-aziatische-hoornaar).
@jrhillae is het niet wat vreemd dat het pdf document aan de JIRA output is gekoppeld? Beter lijkt me het in PURE als aparte output te maken (en te koppelen aan je JIRA output)

2023-09-26 06:53 UTC, peterdesmet commented on pages/nl/get-involved.md
> +Het protocol van zenderen Aziatische hoornaar is beschikbaar via deze [link](https://pureportal.inbo.be/nl/publications/output-2023-protocol-zenderen-aziatische-hoornaar).
Voor taalhelderheid is "link" niet zo handig. Ik zou het schrijven als:

> Gebruik [deze handleiding]() voor het zenderen van Aziatische hoornaar.

2023-09-26 06:58 UTC, peterdesmet commented on pages/nl/get-involved.md
> +Het protocol van zenderen Aziatische hoornaar is beschikbaar via deze [link](https://pureportal.inbo.be/nl/publications/output-2023-protocol-zenderen-aziatische-hoornaar).
Deze info mag ook aan de Engelse pagina worden toegevoegd aangezien beide pagina's verder in sync zijn.

2023-09-26 09:38 UTC, peterdesmet commented on pages/nl/become-eradicator.md
> +Bestrijding met **diatomeeënaarde** is mogelijk tot 15/12/2023.
Samenvoegen in 1 paragraaf

2023-09-26 10:15 UTC, jrhillae commented on pages/nl/get-involved.md
> +Het protocol van zenderen Aziatische hoornaar is beschikbaar via deze [link](https://pureportal.inbo.be/nl/publications/output-2023-protocol-zenderen-aziatische-hoornaar).
@peterdesmet : De huidige link is goedgekeurd en zal ik nu niet meer veranderen want al verspreid in huidige vorm maar in de toekomst zal ik idd outputs steeds eerst afzonderlijk in Pure aanmaken en ze pas achteraf linken aan JIRA. Ik heb de zin aangepast en ook toegevoegd aan Engelstalige pagina. De paragraaf over bestrijding op Engelstalige pagina was niet langer up-to-date en heb ik verwijderd.

2023-10-19 04:24 UTC, jrhillae commented on pages/nl/faq.md
> +{:id="Nest in Brussel, Wallonië of Nederland"}
aangepast

2023-10-19 04:25 UTC, jrhillae commented on pages/nl/faq.md
> +Dit platform Vespa-Watch monitort echter enkel nesten in **Vlaanderen** (België), dus niet nesten die gelegen zijn in Brussel, Wallonië of Nederland.
aangepast

2023-10-19 04:25 UTC, jrhillae commented on pages/nl/faq.md
> +Best kan je je nest melden via volgende sites indien het nest zich bevindt in:
aangepast

2023-10-19 04:26 UTC, jrhillae commented on pages/nl/faq.md
> +- **Nederland**: [Waarnemingen.nl](https://waarneming.nl/go/vespa-velutina/ )
aangepast

2023-10-19 04:36 UTC, jrhillae commented on pages/nl/become-eradicator.md
> +Bestrijding met **diatomeeënaarde** is mogelijk tot 15/12/2023.
Paragraaf over diatomeeënaarde is samengevoegd tot 1 paragraaf.

2023-10-19 04:45 UTC, merged