567 beëindiging verdelging oost vlaanderen
inbo/vespa-watch pull request #568
Opened 2023-10-30 08:44 UTC by CatoCoordinator

Dit zijn **dringende aanpassingen** aangezien Oost-Vlaanderen hun tactiek wijzigt op 6 november. 
@PietrH of @peterdesmet zouden jullie dit zo snel mogelijk willen goedkeuren alstublieft?
Dankjewel!

2023-10-30 15:44 UTC, PietrH requested changes
- It's a bit strange for an English page to refer to Dutch only websites, but I suppose it's the best we can do. 
- We can refer to the same language version of 1722 as the page, that'll save people a click :+1: , you can accept my suggestions if you agree. 
- Made some suggestions to the English wording, which sounded rather formal to me. Feel free to ignore. 

Other than that, tested locally and works. All links resolve.

2023-10-30 15:44 UTC, PietrH commented on pages/nl/faq.md
> +- In **Oost-Vlaanderen** worden vanaf 6 november 2023 de nesten niet langer kosteloos bestreden. Hier vindt u de [procedure](https://oost-vlaanderen.be/wonen-en-leven/natuur-en-milieu/overlastsoorten
```suggestion
- In **Oost-Vlaanderen** worden vanaf 6 november 2023 de nesten niet langer kosteloos bestreden. Hier vindt u de [procedure](https://oost-vlaanderen.be/wonen-en-leven/natuur-en-milieu/overlastsoorten/aziatische-hoornaar.html) terug voor Oost-Vlaanderen. U kan zelf contact opnemen met een private bestrijder (overzicht beschikbaar op [de lijst van bestrijders](https://vespawatch.be/eradicators/)) of de brandweer ([1722](https://www.1722.be/nl/index.html)) indien u dit nest wilt laten verwijderen, wat op eigen kosten is.
```

2023-10-30 15:44 UTC, PietrH commented on pages/nl/faq.md
> +- In **Oost-Vlaanderen** worden vanaf 6 november 2023 de nesten niet langer kosteloos bestreden. Hier vindt u de [procedure](https://oost-vlaanderen.be/wonen-en-leven/natuur-en-milieu/overlastsoorten
```suggestion
- In **Oost-Vlaanderen** worden vanaf 6 november 2023 de nesten niet langer kosteloos bestreden. Hier vindt u de [procedure](https://oost-vlaanderen.be/wonen-en-leven/natuur-en-milieu/overlastsoorten/aziatische-hoornaar.html) terug voor Oost-Vlaanderen. U kan zelf contact opnemen met een private bestrijder (overzicht beschikbaar op [de lijst van bestrijders](https://vespawatch.be/eradicators/)) of de brandweer ([1722](https://www.1722.be/nl/index.html)) indien u dit nest wilt laten verwijderen, wat op eigen kosten is.
```

2023-10-30 15:44 UTC, PietrH commented on pages/nl/report-nest.md
> +- In **Oost-Vlaanderen** worden vanaf 6 november 2023 de nesten niet langer kosteloos bestreden. Hier vindt u de [procedure](https://oost-vlaanderen.be/wonen-en-leven/natuur-en-milieu/overlastsoorten
```suggestion
- In **Oost-Vlaanderen** worden vanaf 6 november 2023 de nesten niet langer kosteloos bestreden. Hier vindt u de [procedure](https://oost-vlaanderen.be/wonen-en-leven/natuur-en-milieu/overlastsoorten/aziatische-hoornaar.html) terug voor Oost-Vlaanderen. U kan zelf contact opnemen met een private bestrijder (overzicht beschikbaar op [de lijst van bestrijders](https://vespawatch.be/eradicators/)) of de brandweer ([1722](https://www.1722.be/nl/index.html)) indien u dit nest wilt laten verwijderen, wat op eigen kosten is.
```

2023-10-30 15:44 UTC, PietrH commented on pages/en/report-nest.md
> +- In **West Flanders** (except Middelkerke), all nests have been removed free of charge since August 1, 2023. If you wish to take advantage of this service, you don't need to do anything after your r
```suggestion
- In **West Flanders** (except Middelkerke), all reported nests are being removed free of charge since August 1, 2023. If you want to take advantage of this service, you don't need to do anything after reporting your sighting on vespawatch.be. If a better picture is needed to confirm it is indeed the nest of an Asian hornet, they will get in touch with you. Once the sighting is validated,  it will be forwarded to the right exterminator. Please be aware that there a bit of a wait. If you want to have a nest removed quickly, you can contact a professional exterminator at your own expense.
```

2023-10-30 15:44 UTC, PietrH commented on pages/en/report-nest.md
> +- In **East Flanders**, from 6 November 2023, nests of the Asian hornet will no longer be controlled free of charge. You can find the procedure for East Flanders [here](https://oost-vlaanderen.be/won
```suggestion
- In **East Flanders**, from 6 November 2023, nests of the Asian hornet will no longer be removed for free. You can find more details [here](https://oost-vlaanderen.be/wonen-en-leven/natuur-en-milieu/overlastsoorten/aziatische-hoornaar.html). You can either hire a private exterminator yourself (overview available on the [list of eradicators](https://vespawatch.be/eradicators/)) or the [fire brigade](https://1722.be/en/index.html) if you want to have this nest removed.
```

2023-10-30 15:44 UTC, PietrH commented on pages/en/report-nest.md
> +- In **Flemish Brabant**, specific municipalities have their own programs: [Begijnendijk](https://www.begijnendijk.be/subsidie-voor-neutralisatie-aziatische-hoornaar), [Tremelo](https://www.tremelo.b
```suggestion
- In **Flemish Brabant**, certain municipalities have their own programs: [Begijnendijk](https://www.begijnendijk.be/subsidie-voor-neutralisatie-aziatische-hoornaar), [Tremelo](https://www.tremelo.be/product/3399/subsidie-bestrijding-aziatische-hoornaar), [Keerbergen](https://www.keerbergen.be/file/download/13055/A0D93C95A2B650AFF95B4DD8F1169F3C), [Boortmeerbeek](https://www.boortmeerbeek.be/subsidie-bestrijding-aziatische-hoornaar) en [Leuven](https://leuven.be/aziatische-hoornaar). More information can be found on the websites of these municipalities.
```

2023-10-31 06:47 UTC, CatoCoordinator commented
> Little extra question, should there be an English FAQ?

Er zou een Engelse FAQ komen, daar zijn ze momenteel mee bezig, maar ik moest nu de snelle aanpassingen doorvoeren zoals de veranderingen in bestrijding van Oost-Vlaanderen.

2023-10-31 06:48 UTC, merged

2023-10-31 06:52 UTC, CatoCoordinator commented
> * It's a bit strange for an English page to refer to Dutch only websites, but I suppose it's the best we can do.
> * We can refer to the same language version of 1722 as the page, that'll save people a click 👍 , you can accept my suggestions if you agree.
> * Made some suggestions to the English wording, which sounded rather formal to me. Feel free to ignore.
> 
> Other than that, tested locally and works. All links resolve.

Dankjewel voor de feedback! Ik heb ze toegepast ;)