Einde verdelging
inbo/vespa-watch pull request #572
Opened 2023-11-08 14:18 UTC by CatoCoordinator

Aanpassingen voor zowel West-Vlaanderen als Oost-Vlaanderen voor het einde van het verdelgingseizoen op de Nederlandse en Engelse sites.

@jrhillae, @PietrH of @peterdesmet zouden jullie dit snel willen goedkeuren alstublieft? Zo zijn de burgers tijdig geïnformeerd. Heb dit nieuws net ontvangen. Alvast bedankt!

2023-11-08 19:37 UTC, jrhillae commented
@CatoCoordinator: wil je de link naar private bestrijders verwijderen uit de uitleg? Zoals ik eerder al aangaf, plaatsen we bewust de link naar private bestrijders uit elke uitleg op de website zodat melders gemotiveerd blijven te melden. Wel geven we aan dat het overzicht wordt verkregen na melding. Ze krijgen het overzicht enkel te zien na melding van een nest. Geef je hier een seintje als dit is verbeterd? Dan kijk ik het opnieuw na.

2023-11-09 07:30 UTC, CatoCoordinator commented
> @CatoCoordinator: wil je de link naar private bestrijders verwijderen uit de uitleg? Zoals ik eerder al aangaf, plaatsen we bewust de link naar private bestrijders uit elke uitleg op de website zodat melders gemotiveerd blijven te melden. Wel geven we aan dat het overzicht wordt verkregen na melding. Ze krijgen het overzicht enkel te zien na melding van een nest. Geef je hier een seintje als dit is verbeterd? Dan kijk ik het opnieuw na.

@jrhillae , Ik heb het gewist. Keur je het goed? 
Ps: Er staat nog een branch open voor de gemeentes voor Vlaams-Brabant.

2023-11-09 08:36 UTC, jrhillae requested changes
@CatoCoordinator : Wil je nog juist de link naar brandweer ook verwijderen in de uitleg? We hebben afgesproken met brandweer dat we hun niet overladen met oproepen en dus in de eerste plaats verwijzen naar private bestrijderes. Enkel in een zin waar er expliciet 'acuut gevaar' wordt vermeld kan de verwijzing naar brandweer worden vermeld.

2023-11-09 09:02 UTC, CatoCoordinator commented
> @CatoCoordinator : Wil je nog juist de link naar brandweer ook verwijderen in de uitleg? We hebben afgesproken met brandweer dat we hun niet overladen met oproepen en dus in de eerste plaats verwijzen naar private bestrijderes. Enkel in een zin waar er expliciet 'acuut gevaar' wordt vermeld kan de verwijzing naar brandweer worden vermeld.

@jrhillae , ik heb dit nagekeken, maar er staat geen link in het stuk over Oost- en West-Vlaanderen of Vlaams-Brabant waar in de link van de brandweer vermeld staat (zie screenshot).
![image](https://github.com/inbo/vespa-watch/assets/145098932/36c2d213-5eb6-4079-94c8-377f1f0a0c70)

2023-11-09 09:05 UTC, CatoCoordinator commented
> @CatoCoordinator : Wil je nog juist de link naar brandweer ook verwijderen in de uitleg? We hebben afgesproken met brandweer dat we hun niet overladen met oproepen en dus in de eerste plaats verwijzen naar private bestrijderes. Enkel in een zin waar er expliciet 'acuut gevaar' wordt vermeld kan de verwijzing naar brandweer worden vermeld.

@jrhillae, het is verwijderd. Groetjes Cato

2023-11-09 09:24 UTC, jrhillae approved these changes

2023-11-09 09:24 UTC, merged